version: '2'
services:
  mysql:
    image: 'mysql:latest'
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: jdshop
      MYSQL_DATABASE: jdshop
      MYSQL_USER: jdshop
      MYSQL_PASSWORD: jdshop
    ports:
      - '3306:3306'
    volumes:
      - './mysql_data:/var/lib/mysql'